version: '3.8'

services:
  web:
    build: .
    container_name: MUSTAFA3000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: django_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-booking_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: