# Generated by Django 6.0.4 on 2026-04-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
