# Generated by Django 6.0.4 on 2026-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_name_alter_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='ФИО сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=1, max_length=14, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
