# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_phone'),
        ('staff', '0004_update_staff_fields'),
    ]

    operations = [
    ]
