# Generated by Django 6.0.4 on 2026-05-06 11:38

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[common.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
