# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_phone'),
        ('clients', '0004_update_client_fields'),
    ]

    operations = [
    ]
