# Generated by Django 6.0.4 on 2026-04-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuorderspreorders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
