# Generated by Django 6.0.4 on 2026-05-01 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuorderspreorders', '0003_remove_profile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_order_time',
        ),
        migrations.RemoveField(
            model_name='preorderitem',
            name='price_at_order_time',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_ordering_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена при заказе'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='status',
            field=models.CharField(default='processing', max_length=50, verbose_name='Статус предзаказа'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='price_at_ordering_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена при заказе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='processing', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
