# Generated by Django 6.0.4 on 2026-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuorderspreorders', '0005_alter_order_user_alter_preorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('was_given', 'Was_given')], default='processing', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('was_given', 'Was_given')], default='processing', max_length=50, verbose_name='Статус предзаказа'),
        ),
    ]
