# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuorderspreorders', '0006_alter_order_status_alter_preorder_status'),
        ('menuorderspreorders', '0006_update_order_category_and_status_fields'),
    ]

    operations = [
    ]
