# Generated by Django 6.0.4 on 2026-04-16 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('hallstables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starting_at', models.DateTimeField(verbose_name='Время начала')),
                ('ending_at', models.DateTimeField(verbose_name='Время окончания')),
                ('guest_count', models.IntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('qr_code', models.CharField(max_length=255, verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client', verbose_name='Клиент')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hallstables.table', verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-starting_at'],
            },
        ),
    ]
