# Generated by Django 6.0.4 on 2026-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_at', models.DateTimeField(verbose_name='Время начала')),
                ('ending_at', models.DateTimeField(verbose_name='Время окончания')),
                ('guest_count', models.IntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('guest_arrived', 'Guest Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=50, verbose_name='Статус')),
                ('qr_code', models.CharField(blank=True, max_length=255, verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['starting_at'],
            },
        ),
    ]
