# Generated by Django 6.0.4 on 2026-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Состояние'),
        ),
    ]
