# Generated by Django 6.0.4 on 2026-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('guest_arrived', 'Guest Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50, verbose_name='Состояние'),
        ),
    ]
