# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
        ('booking', '0003_update_booking_status_and_qr_code'),
    ]

    operations = [
    ]
