# Generated by Django 6.0.4 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_20260508_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('guest_arrived', 'Guest Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
