# Generated by Django 6.0.4 on 2026-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallstables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
