# Generated by Django 6.0.4 on 2026-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallstables', '0002_alter_hall_name_alter_table_name_alter_table_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('out_of_service', 'Out_of_service')], default='available', max_length=20, verbose_name='Состояние'),
        ),
    ]
