# Generated by Django 6.0.4 on 2026-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallstables', '0003_alter_table_status'),
        ('hallstables', '0003_update_hall_and_table_fields'),
    ]

    operations = [
    ]
