# Generated by Django 6.0.4 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallstables', '0004_merge_20260508_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='height',
            field=models.FloatField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='width',
            field=models.FloatField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название стола'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('out_of_service', 'Out of service')], default='available', max_length=20, verbose_name='Статус'),
        ),
    ]
